#!/bin/bash
#Kubo von Kvorkenstein, 2024
compile="gfortran-12 -Ofast -march=native -flto=auto -fwhole-program -fopenmp"

$compile -c harm_synthesis/math/Math.f90
$compile -c harm_synthesis/math/Harmsy.f90
$compile -c harm_synthesis/math/Vector_analysis.f90
$compile -c harm_synthesis/ocean/mod/OutputOceanMod.f90
$compile -c harm_synthesis/ocean/mod/smod/*.f90

$compile harm_synthesis/ocean/OutputOcean.f90 *.o -o code_out

./code_out
rm *.o *.smod *.mod code_out